feature/exercicio1
rhorauti/Orion-Bootcamp pull request #1
Opened 2023-10-09 11:57 UTC by rhorauti

2023-10-09 22:22 UTC, arthurpaesrizon commented
Não é necessário comittar o node_modules.
Podes  criar o arquivo .gitignore e acrescentar o node_modules de fato que ele seja ignorado na hora de subir os arquivos para a branch remota

2023-10-09 22:25 UTC, arthurpaesrizon requested changes

2023-10-09 22:25 UTC, arthurpaesrizon commented on src/app.ts
> +function retornarQtdVogais(palavra: string) {
Podes tipar os retornos das funções

2023-10-09 22:25 UTC, arthurpaesrizon commented on src/app.ts
> +    let qtdVogais = 0
Podes tipar as variáveis também

2023-10-09 22:25 UTC, arthurpaesrizon commented on src/app.ts
> +    const arrayPalavra = palavra.split('');
Podes verificar se o usuário de fato digitou uma palavra para o caso de undefined
Ficaria algo como palavra?.split

2023-10-09 22:42 UTC, carlosrizon commented on src/app.ts
> +        vogais.forEach((vogal: string) => {
O código ta muito repetitivo, você pode reaproveitar a função do primeiro exercicio.

2023-10-09 22:42 UTC, carlosrizon commented on package.json
> +    "typescript": "^5.2.2"
Uma boa prática, sempre fixar as versões.

2023-10-10 18:33 UTC, rhorauti commented on src/app.ts
> +function retornarQtdVogais(palavra: string) {
Ok. Inserido a tipagem no retorno da função.

2023-10-10 18:34 UTC, rhorauti commented on src/app.ts
> +    let qtdVogais = 0
Ok. Inserido tipagem nas variávis

2023-10-10 18:35 UTC, rhorauti commented on src/app.ts
> +    const arrayPalavra = palavra.split('');
Ok. Obrigado. Alterado.

2023-10-10 18:44 UTC, rhorauti commented on src/app.ts
> +        vogais.forEach((vogal: string) => {
Ok. Obrigado. Reaproveitei o retorno da primeira função para inserir na função mostrarQtdVogais

2023-10-11 02:43 UTC, arthurpaesrizon commented on src/app.ts
> +function retornarQtdVogais(palavra: string) {
Faltou só tipar os retornos das outras funções além dessa.

2023-10-11 11:24 UTC, rhorauti commented on src/app.ts
> +function retornarQtdVogais(palavra: string) {
Obrigado pelo comentário Arthur. Eu pensava que por não retornar nada não precisaria. Mas pensando bem inserindo o void fica até explicito que a função não retorna nada.

2023-10-11 22:22 UTC, arthurpaesrizon approved these changes

2023-10-11 22:22 UTC, merged