feature/exercicio2
rhorauti/Orion-Bootcamp pull request #2
Opened 2023-10-10 00:38 UTC by rhorauti

2023-10-12 02:37 UTC, carlosrizon requested changes

2023-10-12 02:37 UTC, carlosrizon commented on src/exercicio2-funcional.ts
> +    for(let i=0; i<lista.length; i++) {
Aqui deve usar o paradigma funcional, considere utilizar o "[filter](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)" e "[find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)".

2023-10-12 02:40 UTC, carlosrizon requested changes

2023-10-12 02:40 UTC, carlosrizon commented on dist/exercicio2-funcional.js
> +"use strict";
Os aquivos dist não devem subir ao repo, verifique o seu gitignore, você pode remover o .dist do gitignore excluir os arquivos e commitar, ai sim adicione novamente o .dist dentro do gitignore e commite novamente.

2023-10-12 22:34 UTC, rhorauti commented on src/exercicio2-funcional.ts
> +    for(let i=0; i<lista.length; i++) {
Obrigado Carlos. Usei o find no lugar do for

2023-10-12 22:35 UTC, rhorauti commented on dist/exercicio2-funcional.js
> +"use strict";
Ok. Obrigado Carlos. Já inseri a pasta dist no arquivo .gitignore

2023-10-13 13:24 UTC, carlosrizon approved these changes

2023-10-13 13:24 UTC, merged